%% MACHINE-LEARNING POWER ESTIMATOR FOR DIGITAL CIRCUITS
%
% Project:
%   ML_Digital_Power_Estimator
%
% Objective:
%   Estimate the approximate dynamic power consumption of a digital
%   circuit using its design and operating parameters.
%
% Simplified physical relationship:
%
%       P_dynamic = alpha * C * V^2 * f
%
% The program:
%   1. Generates or loads a synthetic circuit dataset
%   2. Creates an 80/20 training and testing split
%   3. Evaluates the physical formula baseline
%   4. Trains raw-feature ridge regression
%   5. Trains physics-informed ridge regression
%   6. Compares the models
%   7. Saves the best trained model
%   8. Estimates power for a new circuit
%   9. Generates analysis plots
%
% No Statistics and Machine Learning Toolbox is required.
%
% Recommended filename:
%   power_estimator.m

clear;
clc;
close all;

rng(42, 'twister');

%% ------------------------------------------------------------
% PROJECT CONFIGURATION
% -------------------------------------------------------------

projectRoot = fileparts(mfilename('fullpath'));

if isempty(projectRoot)
    projectRoot = pwd;
end

datasetPath = fullfile( ...
    projectRoot, ...
    'digital_power_dataset.csv');

resultsPath = fullfile( ...
    projectRoot, ...
    'power_model_results.csv');

modelPath = fullfile( ...
    projectRoot, ...
    'trained_power_estimator.mat');

numberOfSamples = 6000;

% Set to true to overwrite and regenerate the dataset.
regenerateDataset = true;

fprintf('Machine-Learning Digital Circuit Power Estimator\n');
fprintf('================================================\n\n');

%% ------------------------------------------------------------
% LOAD OR GENERATE DATASET
% -------------------------------------------------------------

datasetExists = exist(datasetPath, 'file') == 2;

if regenerateDataset || ~datasetExists

    fprintf( ...
        'Generating %d circuit configurations...\n', ...
        numberOfSamples);

    dataset = generatePowerDataset(numberOfSamples);

    writetable(dataset, datasetPath);

    fprintf( ...
        'Dataset saved to:\n%s\n\n', ...
        datasetPath);

else

    fprintf('Loading existing dataset...\n');

    dataset = readtable(datasetPath);

    fprintf( ...
        'Loaded %d circuit records from:\n%s\n\n', ...
        height(dataset), ...
        datasetPath);

end

%% ------------------------------------------------------------
% VALIDATE DATASET
% -------------------------------------------------------------

requiredVariables = { ...
    'SwitchingActivity', ...
    'Capacitance_pF', ...
    'Voltage_V', ...
    'Frequency_MHz', ...
    'GateCount', ...
    'FanOut', ...
    'Temperature_C', ...
    'ProcessFactor', ...
    'DynamicPower_mW' ...
};

availableVariables = dataset.Properties.VariableNames;

missingVariables = setdiff( ...
    requiredVariables, ...
    availableVariables);

if ~isempty(missingVariables)

    error( ...
        'Dataset is missing these variables: %s', ...
        strjoin(missingVariables, ', '));

end

if height(dataset) < 10

    error( ...
        'The dataset must contain at least 10 rows.');

end

disp('First ten circuit records:');
disp(dataset(1:min(10, height(dataset)), :));

%% ------------------------------------------------------------
% DEFINE INPUT FEATURES AND TARGET
% -------------------------------------------------------------

predictorNames = { ...
    'SwitchingActivity', ...
    'Capacitance_pF', ...
    'Voltage_V', ...
    'Frequency_MHz', ...
    'GateCount', ...
    'FanOut', ...
    'Temperature_C', ...
    'ProcessFactor' ...
};

X = table2array( ...
    dataset(:, predictorNames));

Y = dataset.DynamicPower_mW;

X = double(X);
Y = double(Y(:));

if any(~isfinite(X(:))) || any(~isfinite(Y))

    error( ...
        'The dataset contains NaN or infinite values.');

end

%% ------------------------------------------------------------
% CREATE TRAINING AND TESTING DATA
% -------------------------------------------------------------

% Deterministic 80/20 split.
% Every fifth row is assigned to the test set.

rowNumbers = (1:height(dataset))';

testMask = mod(rowNumbers, 5) == 0;
trainingMask = ~testMask;

XTrain = X(trainingMask, :);
YTrain = Y(trainingMask);

XTest = X(testMask, :);
YTest = Y(testMask);

fprintf( ...
    'Training samples: %d\n', ...
    size(XTrain, 1));

fprintf( ...
    'Testing samples : %d\n\n', ...
    size(XTest, 1));

%% ------------------------------------------------------------
% MODEL 1: PHYSICS FORMULA BASELINE
% -------------------------------------------------------------

physicsPredictions = ...
    XTest(:, 1) .* ...
    XTest(:, 2) .* ...
    XTest(:, 3).^2 .* ...
    XTest(:, 4) .* ...
    1e-3;

physicsMetrics = calculateRegressionMetrics( ...
    YTest, ...
    physicsPredictions);

%% ------------------------------------------------------------
% MODEL 2: RAW-FEATURE RIDGE REGRESSION
% -------------------------------------------------------------

rawFeatureMode = 'raw';
rawLambda = 0.10;

[rawTrainingFeatures, rawFeatureNames] = ...
    buildFeatureMatrix( ...
        XTrain, ...
        rawFeatureMode);

rawTestingFeatures = buildFeatureMatrix( ...
    XTest, ...
    rawFeatureMode);

rawModel = fitRidgeModel( ...
    rawTrainingFeatures, ...
    YTrain, ...
    rawLambda, ...
    rawFeatureMode, ...
    rawFeatureNames);

rawPredictions = predictRidgeModel( ...
    rawModel, ...
    rawTestingFeatures);

rawMetrics = calculateRegressionMetrics( ...
    YTest, ...
    rawPredictions);

%% ------------------------------------------------------------
% MODEL 3: PHYSICS-INFORMED RIDGE REGRESSION
% -------------------------------------------------------------

physicsFeatureMode = 'physics_informed';
physicsLambda = 0.01;

[physicsTrainingFeatures, physicsFeatureNames] = ...
    buildFeatureMatrix( ...
        XTrain, ...
        physicsFeatureMode);

physicsTestingFeatures = buildFeatureMatrix( ...
    XTest, ...
    physicsFeatureMode);

physicsInformedModel = fitRidgeModel( ...
    physicsTrainingFeatures, ...
    YTrain, ...
    physicsLambda, ...
    physicsFeatureMode, ...
    physicsFeatureNames);

physicsInformedPredictions = predictRidgeModel( ...
    physicsInformedModel, ...
    physicsTestingFeatures);

physicsInformedMetrics = calculateRegressionMetrics( ...
    YTest, ...
    physicsInformedPredictions);

%% ------------------------------------------------------------
% COMPARE MODEL PERFORMANCE
% -------------------------------------------------------------

modelNames = { ...
    'Physics Formula Baseline'; ...
    'Raw-Feature Ridge Regression'; ...
    'Physics-Informed Ridge Regression' ...
};

RMSE_mW = [ ...
    physicsMetrics.RMSE; ...
    rawMetrics.RMSE; ...
    physicsInformedMetrics.RMSE ...
];

MAE_mW = [ ...
    physicsMetrics.MAE; ...
    rawMetrics.MAE; ...
    physicsInformedMetrics.MAE ...
];

R2 = [ ...
    physicsMetrics.R2; ...
    rawMetrics.R2; ...
    physicsInformedMetrics.R2 ...
];

MAPE_Percent = [ ...
    physicsMetrics.MAPE; ...
    rawMetrics.MAPE; ...
    physicsInformedMetrics.MAPE ...
];

resultsTable = table( ...
    modelNames, ...
    RMSE_mW, ...
    MAE_mW, ...
    R2, ...
    MAPE_Percent, ...
    'VariableNames', { ...
        'Model', ...
        'RMSE_mW', ...
        'MAE_mW', ...
        'R2', ...
        'MAPE_Percent' ...
    });

resultsTable = sortrows( ...
    resultsTable, ...
    'RMSE_mW');

writetable( ...
    resultsTable, ...
    resultsPath);

disp('Model-performance comparison:');
disp(resultsTable);

fprintf( ...
    'Model results saved to:\n%s\n\n', ...
    resultsPath);

%% ------------------------------------------------------------
% SELECT BEST MACHINE-LEARNING MODEL
% -------------------------------------------------------------

trainedModels = { ...
    rawModel; ...
    physicsInformedModel ...
};

trainedMetrics = { ...
    rawMetrics; ...
    physicsInformedMetrics ...
};

trainedPredictions = { ...
    rawPredictions; ...
    physicsInformedPredictions ...
};

trainedModelNames = { ...
    'Raw-Feature Ridge Regression'; ...
    'Physics-Informed Ridge Regression' ...
};

trainedRMSE = [ ...
    rawMetrics.RMSE; ...
    physicsInformedMetrics.RMSE ...
];

[~, bestModelIndex] = min(trainedRMSE);

bestModel = trainedModels{bestModelIndex};
bestMetrics = trainedMetrics{bestModelIndex};
bestPredictions = trainedPredictions{bestModelIndex};
bestModelName = trainedModelNames{bestModelIndex};

%% ------------------------------------------------------------
% SAVE TRAINED MODEL
% -------------------------------------------------------------

modelPackage = struct();

modelPackage.ModelName = bestModelName;
modelPackage.FeatureMode = bestModel.FeatureMode;

modelPackage.PredictorNames = predictorNames;
modelPackage.FeatureNames = bestModel.FeatureNames;

modelPackage.Mu = bestModel.Mu;
modelPackage.Sigma = bestModel.Sigma;
modelPackage.Beta = bestModel.Beta;
modelPackage.Lambda = bestModel.Lambda;

modelPackage.RMSE_mW = bestMetrics.RMSE;
modelPackage.MAE_mW = bestMetrics.MAE;
modelPackage.R2 = bestMetrics.R2;
modelPackage.MAPE_Percent = bestMetrics.MAPE;

modelPackage.TrainingSamples = size(XTrain, 1);
modelPackage.TestSamples = size(XTest, 1);

modelPackage.CreatedOn = datestr(now, 30);

modelPackage.Description = ...
    'Physics-informed digital dynamic-power estimator.';

save( ...
    modelPath, ...
    'modelPackage');

fprintf('Best trained model\n');
fprintf('------------------\n');

fprintf( ...
    'Model       : %s\n', ...
    modelPackage.ModelName);

fprintf( ...
    'RMSE        : %.6f mW\n', ...
    modelPackage.RMSE_mW);

fprintf( ...
    'MAE         : %.6f mW\n', ...
    modelPackage.MAE_mW);

fprintf( ...
    'R-squared   : %.6f\n', ...
    modelPackage.R2);

fprintf( ...
    'MAPE        : %.4f %%\n', ...
    modelPackage.MAPE_Percent);

fprintf( ...
    'Model saved : %s\n\n', ...
    modelPath);

%% ------------------------------------------------------------
% ESTIMATE POWER FOR A NEW CIRCUIT
% -------------------------------------------------------------

newCircuit = table( ...
    0.18, ...        % Switching activity
    250, ...         % Capacitance in pF
    0.90, ...        % Voltage in V
    500, ...         % Frequency in MHz
    125000, ...      % Gate count
    2.5, ...         % Fan-out
    65, ...          % Temperature in Celsius
    1.02, ...        % Process factor
    'VariableNames', predictorNames);

newCircuitArray = table2array(newCircuit);

newCircuitFeatures = buildFeatureMatrix( ...
    newCircuitArray, ...
    modelPackage.FeatureMode);

estimatedPower_mW = predictRidgeModel( ...
    modelPackage, ...
    newCircuitFeatures);

formulaPower_mW = ...
    newCircuit.SwitchingActivity .* ...
    newCircuit.Capacitance_pF .* ...
    newCircuit.Voltage_V.^2 .* ...
    newCircuit.Frequency_MHz .* ...
    1e-3;

fprintf('New-circuit power estimate\n');
fprintf('--------------------------\n');

fprintf( ...
    'ML-estimated power     : %.6f mW\n', ...
    estimatedPower_mW);

fprintf( ...
    'Formula baseline power : %.6f mW\n', ...
    formulaPower_mW);

fprintf( ...
    'Estimated adjustment   : %.6f mW\n\n', ...
    estimatedPower_mW - formulaPower_mW);

%% ------------------------------------------------------------
% VISUALIZATION 1: ACTUAL VERSUS PREDICTED
% -------------------------------------------------------------

figure( ...
    'Name', ...
    'Actual versus Predicted Power');

scatter( ...
    YTest, ...
    bestPredictions, ...
    20, ...
    'filled');

hold on;

minimumPower = min([YTest; bestPredictions]);
maximumPower = max([YTest; bestPredictions]);

plot( ...
    [minimumPower, maximumPower], ...
    [minimumPower, maximumPower], ...
    'LineWidth', ...
    1.5);

hold off;

xlabel('Actual Dynamic Power (mW)');
ylabel('Predicted Dynamic Power (mW)');
title('Actual versus Predicted Dynamic Power');

grid on;

%% ------------------------------------------------------------
% VISUALIZATION 2: RESIDUAL DISTRIBUTION
% -------------------------------------------------------------

residuals = YTest - bestPredictions;

figure( ...
    'Name', ...
    'Power Prediction Residuals');

histogram( ...
    residuals, ...
    40);

xlabel('Prediction Error (mW)');
ylabel('Number of Test Samples');
title('Distribution of Power-Prediction Errors');

grid on;

%% ------------------------------------------------------------
% VISUALIZATION 3: MODEL COMPARISON
% -------------------------------------------------------------

figure( ...
    'Name', ...
    'Model RMSE Comparison');

bar(RMSE_mW);

set( ...
    gca, ...
    'XTick', ...
    1:numel(modelNames), ...
    'XTickLabel', ...
    modelNames);

ylabel('RMSE (mW)');
title('Digital-Power Estimator Comparison');

grid on;

%% ------------------------------------------------------------
% VISUALIZATION 4: FEATURE IMPORTANCE
% -------------------------------------------------------------

featureImportance = abs( ...
    modelPackage.Beta(2:end));

importanceTotal = sum(featureImportance);

if importanceTotal > 0

    featureImportance = ...
        featureImportance ./ importanceTotal;

end

figure( ...
    'Name', ...
    'Feature Importance');

bar(featureImportance);

set( ...
    gca, ...
    'XTick', ...
    1:numel(modelPackage.FeatureNames), ...
    'XTickLabel', ...
    modelPackage.FeatureNames);

ylabel('Relative Absolute Coefficient');
title('Physics-Informed Feature Importance');

grid on;

% Rotate labels when the installed MATLAB version supports it.
if exist('xtickangle', 'file') == 2
    xtickangle(45);
end

%% ------------------------------------------------------------
% VISUALIZATION 5: VOLTAGE DESIGN SPACE
% -------------------------------------------------------------

voltageRange = linspace( ...
    0.60, ...
    1.20, ...
    100)';

voltageExperiment = repmat( ...
    newCircuitArray, ...
    numel(voltageRange), ...
    1);

voltageExperiment(:, 3) = voltageRange;

voltageFeatures = buildFeatureMatrix( ...
    voltageExperiment, ...
    modelPackage.FeatureMode);

voltagePredictions = predictRidgeModel( ...
    modelPackage, ...
    voltageFeatures);

figure( ...
    'Name', ...
    'Voltage versus Power');

plot( ...
    voltageRange, ...
    voltagePredictions, ...
    'LineWidth', ...
    1.5);

xlabel('Supply Voltage (V)');
ylabel('Predicted Dynamic Power (mW)');
title('Effect of Supply Voltage on Dynamic Power');

grid on;

%% ------------------------------------------------------------
% VISUALIZATION 6: FREQUENCY DESIGN SPACE
% -------------------------------------------------------------

frequencyRange = linspace( ...
    50, ...
    1000, ...
    100)';

frequencyExperiment = repmat( ...
    newCircuitArray, ...
    numel(frequencyRange), ...
    1);

frequencyExperiment(:, 4) = frequencyRange;

frequencyFeatures = buildFeatureMatrix( ...
    frequencyExperiment, ...
    modelPackage.FeatureMode);

frequencyPredictions = predictRidgeModel( ...
    modelPackage, ...
    frequencyFeatures);

figure( ...
    'Name', ...
    'Frequency versus Power');

plot( ...
    frequencyRange, ...
    frequencyPredictions, ...
    'LineWidth', ...
    1.5);

xlabel('Operating Frequency (MHz)');
ylabel('Predicted Dynamic Power (mW)');
title('Effect of Frequency on Dynamic Power');

grid on;

fprintf('Project execution completed successfully.\n');

%% ============================================================
% LOCAL FUNCTION: GENERATE SYNTHETIC DATASET
% =============================================================

function dataset = generatePowerDataset(numberOfSamples)

    if nargin < 1
        numberOfSamples = 6000;
    end

    if ~isscalar(numberOfSamples) || ...
            ~isnumeric(numberOfSamples) || ...
            ~isfinite(numberOfSamples) || ...
            numberOfSamples < 1 || ...
            fix(numberOfSamples) ~= numberOfSamples

        error( ...
            'numberOfSamples must be a positive integer.');

    end

    %% Switching activity

    switchingActivity = ...
        0.01 + ...
        (0.50 - 0.01) .* ...
        rand(numberOfSamples, 1);

    %% Gate count

    gateCount = randi( ...
        [1000, 500000], ...
        numberOfSamples, ...
        1);

    %% Effective capacitance

    capacitanceVariation = ...
        0.75 + ...
        (1.25 - 0.75) .* ...
        rand(numberOfSamples, 1);

    capacitance_pF = ...
        0.002 .* ...
        double(gateCount) .* ...
        capacitanceVariation;

    %% Supply voltage

    voltage_V = ...
        0.60 + ...
        (1.20 - 0.60) .* ...
        rand(numberOfSamples, 1);

    %% Operating frequency

    frequency_MHz = ...
        50 + ...
        (1000 - 50) .* ...
        rand(numberOfSamples, 1);

    %% Average fan-out

    fanOut = ...
        1 + ...
        (5 - 1) .* ...
        rand(numberOfSamples, 1);

    %% Operating temperature

    temperature_C = ...
        25 + ...
        (100 - 25) .* ...
        rand(numberOfSamples, 1);

    %% Semiconductor process variation

    processFactor = ...
        0.90 + ...
        (1.10 - 0.90) .* ...
        rand(numberOfSamples, 1);

    %% Simplified dynamic power

    % With capacitance in pF and frequency in MHz:
    %
    % P_mW = alpha * C_pF * V^2 * f_MHz * 10^-3

    basePower_mW = ...
        switchingActivity .* ...
        capacitance_pF .* ...
        voltage_V.^2 .* ...
        frequency_MHz .* ...
        1e-3;

    %% Fan-out correction

    fanOutFactor = ...
        1 + ...
        0.04 .* ...
        (fanOut - 1);

    %% Temperature correction

    temperatureFactor = ...
        1 + ...
        0.0015 .* ...
        (temperature_C - 25);

    %% Corrected dynamic power

    correctedPower_mW = ...
        basePower_mW .* ...
        fanOutFactor .* ...
        temperatureFactor .* ...
        processFactor;

    %% Add simulated observation noise

    noiseStandardDeviation = ...
        0.03 .* ...
        max(correctedPower_mW, eps);

    randomNoise = ...
        noiseStandardDeviation .* ...
        randn(numberOfSamples, 1);

    dynamicPower_mW = ...
        correctedPower_mW + randomNoise;

    dynamicPower_mW = ...
        max(dynamicPower_mW, 0);

    %% Force all variables to column vectors

    switchingActivity = switchingActivity(:);
    capacitance_pF = capacitance_pF(:);
    voltage_V = voltage_V(:);
    frequency_MHz = frequency_MHz(:);
    gateCount = gateCount(:);
    fanOut = fanOut(:);
    temperature_C = temperature_C(:);
    processFactor = processFactor(:);
    dynamicPower_mW = dynamicPower_mW(:);

    %% Validate generated vector sizes

    expectedRows = numberOfSamples;

    generatedRowCounts = [ ...
        numel(switchingActivity), ...
        numel(capacitance_pF), ...
        numel(voltage_V), ...
        numel(frequency_MHz), ...
        numel(gateCount), ...
        numel(fanOut), ...
        numel(temperature_C), ...
        numel(processFactor), ...
        numel(dynamicPower_mW) ...
    ];

    if any(generatedRowCounts ~= expectedRows)

        error( ...
            'One or more generated variables have an invalid size.');

    end

    %% Create dataset table

    dataset = table( ...
        switchingActivity, ...
        capacitance_pF, ...
        voltage_V, ...
        frequency_MHz, ...
        gateCount, ...
        fanOut, ...
        temperature_C, ...
        processFactor, ...
        dynamicPower_mW, ...
        'VariableNames', { ...
            'SwitchingActivity', ...
            'Capacitance_pF', ...
            'Voltage_V', ...
            'Frequency_MHz', ...
            'GateCount', ...
            'FanOut', ...
            'Temperature_C', ...
            'ProcessFactor', ...
            'DynamicPower_mW' ...
        });

end

%% ============================================================
% LOCAL FUNCTION: BUILD FEATURE MATRIX
% =============================================================

function [features, featureNames] = buildFeatureMatrix( ...
    circuitInputs, ...
    featureMode)

    if size(circuitInputs, 2) ~= 8

        error( ...
            'circuitInputs must have exactly eight columns.');

    end

    rawFeatureNames = { ...
        'SwitchingActivity'; ...
        'Capacitance_pF'; ...
        'Voltage_V'; ...
        'Frequency_MHz'; ...
        'GateCount'; ...
        'FanOut'; ...
        'Temperature_C'; ...
        'ProcessFactor' ...
    };

    if strcmp(featureMode, 'raw')

        features = circuitInputs;
        featureNames = rawFeatureNames;

        return;

    end

    if ~strcmp(featureMode, 'physics_informed')

        error( ...
            'Unknown feature mode: %s', ...
            featureMode);

    end

    alpha = circuitInputs(:, 1);
    capacitance = circuitInputs(:, 2);
    voltage = circuitInputs(:, 3);
    frequency = circuitInputs(:, 4);

    fanOut = circuitInputs(:, 6);
    temperature = circuitInputs(:, 7);
    processFactor = circuitInputs(:, 8);

    basePower_mW = ...
        alpha .* ...
        capacitance .* ...
        voltage.^2 .* ...
        frequency .* ...
        1e-3;

    % IMPORTANT:
    % Commas are used to concatenate features horizontally.
    %
    % Each row remains one circuit sample.

    features = [ ...
        circuitInputs, ...
        basePower_mW, ...
        basePower_mW .* fanOut, ...
        basePower_mW .* temperature, ...
        basePower_mW .* processFactor, ...
        basePower_mW .* fanOut .* processFactor, ...
        basePower_mW .* temperature .* processFactor, ...
        basePower_mW .* fanOut .* temperature .* processFactor ...
    ];

    featureNames = [ ...
        rawFeatureNames; ...
        { ...
            'BasePower_mW'; ...
            'BasePower_x_FanOut'; ...
            'BasePower_x_Temperature'; ...
            'BasePower_x_Process'; ...
            'BasePower_x_FanOut_x_Process'; ...
            'BasePower_x_Temperature_x_Process'; ...
            'BasePower_x_FanOut_x_Temperature_x_Process' ...
        } ...
    ];

end

%% ============================================================
% LOCAL FUNCTION: TRAIN RIDGE REGRESSION
% =============================================================

function model = fitRidgeModel( ...
    trainingFeatures, ...
    trainingTarget, ...
    lambda, ...
    featureMode, ...
    featureNames)

    if size(trainingFeatures, 1) ~= numel(trainingTarget)

        error( ...
            ['The number of training-feature rows must match ', ...
             'the number of target values.']);

    end

    if lambda < 0 || ~isfinite(lambda)

        error( ...
            'The ridge regularization value must be nonnegative.');

    end

    trainingTarget = trainingTarget(:);

    %% Calculate feature scaling parameters

    featureMean = mean( ...
        trainingFeatures, ...
        1);

    featureStandardDeviation = std( ...
        trainingFeatures, ...
        0, ...
        1);

    % Prevent division by zero for constant features.
    featureStandardDeviation( ...
        featureStandardDeviation == 0) = 1;

    %% Standardize features

    standardizedFeatures = bsxfun( ...
        @rdivide, ...
        bsxfun( ...
            @minus, ...
            trainingFeatures, ...
            featureMean), ...
        featureStandardDeviation);

    %% Add intercept column

    % IMPORTANT:
    % The intercept and standardized features must be concatenated
    % horizontally.

    designMatrix = [ ...
        ones(size(standardizedFeatures, 1), 1), ...
        standardizedFeatures ...
    ];

    %% Create ridge regularization matrix

    numberOfCoefficients = size(designMatrix, 2);

    regularizationMatrix = eye(numberOfCoefficients);

    % Do not regularize the intercept.
    regularizationMatrix(1, 1) = 0;

    %% Solve ridge regression

    coefficientMatrix = ...
        designMatrix' * designMatrix + ...
        lambda .* regularizationMatrix;

    targetVector = ...
        designMatrix' * trainingTarget;

    coefficients = ...
        coefficientMatrix \ targetVector;

    %% Store model

    model = struct();

    model.FeatureMode = featureMode;
    model.FeatureNames = featureNames;

    model.Mu = featureMean;
    model.Sigma = featureStandardDeviation;

    model.Beta = coefficients;
    model.Lambda = lambda;

end

%% ============================================================
% LOCAL FUNCTION: PREDICT USING RIDGE MODEL
% =============================================================

function predictions = predictRidgeModel( ...
    model, ...
    features)

    if size(features, 2) ~= numel(model.Mu)

        error( ...
            ['The prediction feature count does not match ', ...
             'the trained model.']);

    end

    %% Standardize input features

    standardizedFeatures = bsxfun( ...
        @rdivide, ...
        bsxfun( ...
            @minus, ...
            features, ...
            model.Mu), ...
        model.Sigma);

    %% Create design matrix

    designMatrix = [ ...
        ones(size(standardizedFeatures, 1), 1), ...
        standardizedFeatures ...
    ];

    %% Generate predictions

    predictions = ...
        designMatrix * model.Beta;

    % Dynamic power cannot be negative.
    predictions = max(predictions, 0);

end

%% ============================================================
% LOCAL FUNCTION: CALCULATE REGRESSION METRICS
% =============================================================

function metrics = calculateRegressionMetrics( ...
    actualValues, ...
    predictedValues)

    actualValues = actualValues(:);
    predictedValues = predictedValues(:);

    if numel(actualValues) ~= numel(predictedValues)

        error( ...
            ['The actual and predicted arrays must contain ', ...
             'the same number of values.']);

    end

    if isempty(actualValues)

        error( ...
            'Metric calculation requires at least one observation.');

    end

    errors = ...
        actualValues - predictedValues;

    metrics = struct();

    %% Root mean squared error

    metrics.RMSE = sqrt( ...
        mean(errors.^2));

    %% Mean absolute error

    metrics.MAE = mean( ...
        abs(errors));

    %% Coefficient of determination

    totalVariation = sum( ...
        (actualValues - mean(actualValues)).^2);

    if totalVariation > 0

        metrics.R2 = ...
            1 - ...
            sum(errors.^2) ./ ...
            totalVariation;

    else

        metrics.R2 = NaN;

    end

    %% Mean absolute percentage error

    validPercentageRows = ...
        abs(actualValues) > eps;

    if any(validPercentageRows)

        percentageErrors = abs( ...
            errors(validPercentageRows) ./ ...
            actualValues(validPercentageRows));

        metrics.MAPE = ...
            100 .* mean(percentageErrors);

    else

        metrics.MAPE = NaN;

    end

end