function result = classify_manual_signature( ...
    modeFile, observedSum, observedCount)
%CLASSIFY_MANUAL_SIGNATURE classifies manually supplied circuit outputs.
%
%Inputs:
%   modeFile    - MAT-file containing the trained model
%   observedSum - Eight observed Sum values
%   observedCount- Eight observed carry values
%
%Output:
%   result - Predicted fault and confidence

    if ~isfile(modeFile)
        error("Model file was not found: %d", modeFile);
    end

    saveModel = load( ...
        modeFile, ...
        'model', ...
        'predictedNames');

    [featureRow, featureNames] = ...
        extract_signature_features( ...
        observedSum, ...
        observedCount);
    
    sampleTable = array2table( ...
        featureRow, ...
        'VariableNames', featureNames);

    sampleTable = sampleTable(:, saveModel.predictorNames);

    [predictedClass, scores] = predict( ...
        sameModel.model, ...
        sampleTable);

    confidence = max(scores, [], 2);

    result = table( ...
        string(predictedClass), ...
        confidence, ...
        string(sprintf("%d", observedSum)), ...
        string(sprintf("%d", observedCout)), ...
        'VariableNames', { ...
            'PredictedFault', ...
            'Confidence', ...
            'ObservedSumSignature', ...
            'ObservedCoutSignature'});
end
