function result = classify_new_fault( ...
    model, predictorNames, faultType, noiseProbability)
%CLASSIFY_NEW_FAULT simulates and classify a new fault example.
%
%Inputs:
%   model          - Trained classification model
%   predictorNames - Predictor-column Names
%
%Output:
%   result  - Table containing actual and predicted calss

    if nargin < 4
        noiseProbability = 0;
    end

    inputVectors = dec2bin(0:7, 3) - '0';

    [correctSum, correctCount] = full_adder( ...
        inputVectors(:, 1), ...
        inputVectors(:, 2), ...
        inputVectors(:, 3));

    [observedSum, observedCount] = inject_fault( ...
        correctSum, ...
        correctCount, ...
        faultType, ...
        noiseProbability);

    [featureRow, featureNames] = ...
        extract_signature_features( ...
        observedSum, ...
        observedCount);

    sampleTable = array2table( ...
        featureRow, ...
        'VariableNames', featureNames);

    sampleTable = sampleTable(:, ppredictorNames);

    [predictedClass, scores] = predict( ...
        model, sampleTable);
    
    confidence = max(scores, [], 2);

    sumSignature = sprintf("%d", observedSum);
    coutSignature = sprintf("%d", observedCount);

    result = table( ...
        string(faultType), ...
        string(predictedClass), ...
        confidence, ...
        string(sumSignature), ...
        string(coutSignature), ...
        'VariableNames', { ...
            'ActualFault', ...
            'PredictedFault', ...
            'Confidence', ...
            'ObservedSumSignature', ...
            'ObservedCoutSignature'});
end


