function [summaryTable, metricsTable] = evaluate_classifier( ...
    model, testTable, predictorNames)
%EVALUATE_CLASSIFIER Evaluates the trained fault classifier.
%
% Inputs:
%   model          - Trained MATLAB classification model
%   testTable      - Test dataset containing predictor columns and Label
%   predictorNames - Names of columns used as model predictors
%
% Outputs:
%   summaryTable   - Overall classifier-performance summary
%   metricsTable   - Per-class classification metrics

    % ---------------------------------------------------------------
    % Validate inputs
    % ---------------------------------------------------------------
    if nargin < 3
        error(["evaluate_classifier requires model, testTable, " ...
               "and predictorNames."]);
    end

    if ~istable(testTable)
        error("testTable must be a MATLAB table.");
    end

    if ~ismember("Label", string(testTable.Properties.VariableNames))
        error("testTable must contain a column named Label.");
    end

    predictorNames = cellstr(string(predictorNames));

    missingPredictors = setdiff( ...
        predictorNames, testTable.Properties.VariableNames);

    if ~isempty(missingPredictors)
        error( ...
            "Missing predictor columns in testTable: %s", ...
            strjoin(missingPredictors, ", "));
    end

    % ---------------------------------------------------------------
    % Extract predictors and labels
    % ---------------------------------------------------------------
    testPredictors = testTable(:, predictorNames);

    % This assignment fixes the reported error.
    actualLabelText = string(testTable.Label);

    % Generate predictions.
    predictedLabelText = string(predict(model, testPredictors));

    % Ensure column-vector form.
    actualLabelText = actualLabelText(:);
    predictedLabelText = predictedLabelText(:);

    if numel(actualLabelText) ~= numel(predictedLabelText)
        error(["The number of actual labels does not match the " ...
               "number of predicted labels."]);
    end

    % ---------------------------------------------------------------
    % Give both label arrays identical category definitions
    % ---------------------------------------------------------------
    classNames = unique( ...
        [actualLabelText; predictedLabelText], ...
        "stable");

    categoryValues = cellstr(classNames);

    actualLabels = categorical( ...
        cellstr(actualLabelText), ...
        categoryValues, ...
        categoryValues);

    predictedLabels = categorical( ...
        cellstr(predictedLabelText), ...
        categoryValues, ...
        categoryValues);

    % ---------------------------------------------------------------
    % Confusion matrix
    % ---------------------------------------------------------------
    [confusionMatrix, classOrder] = confusionmat( ...
        actualLabels, ...
        predictedLabels);

    numberOfClasses = numel(classOrder);
    totalSamples = numel(actualLabels);

    % ---------------------------------------------------------------
    % Calculate per-class metrics
    % ---------------------------------------------------------------
    truePositive = zeros(numberOfClasses, 1);
    falsePositive = zeros(numberOfClasses, 1);
    falseNegative = zeros(numberOfClasses, 1);
    trueNegative = zeros(numberOfClasses, 1);

    precision = zeros(numberOfClasses, 1);
    recall = zeros(numberOfClasses, 1);
    specificity = zeros(numberOfClasses, 1);
    f1Score = zeros(numberOfClasses, 1);
    support = zeros(numberOfClasses, 1);

    for classIndex = 1:numberOfClasses

        truePositive(classIndex) = ...
            confusionMatrix(classIndex, classIndex);

        falsePositive(classIndex) = ...
            sum(confusionMatrix(:, classIndex)) ...
            - truePositive(classIndex);

        falseNegative(classIndex) = ...
            sum(confusionMatrix(classIndex, :)) ...
            - truePositive(classIndex);

        trueNegative(classIndex) = ...
            sum(confusionMatrix, "all") ...
            - truePositive(classIndex) ...
            - falsePositive(classIndex) ...
            - falseNegative(classIndex);

        support(classIndex) = ...
            sum(confusionMatrix(classIndex, :));

        precision(classIndex) = safe_divide( ...
            truePositive(classIndex), ...
            truePositive(classIndex) + falsePositive(classIndex));

        recall(classIndex) = safe_divide( ...
            truePositive(classIndex), ...
            truePositive(classIndex) + falseNegative(classIndex));

        specificity(classIndex) = safe_divide( ...
            trueNegative(classIndex), ...
            trueNegative(classIndex) + falsePositive(classIndex));

        f1Score(classIndex) = safe_divide( ...
            2 * precision(classIndex) * recall(classIndex), ...
            precision(classIndex) + recall(classIndex));
    end

    metricsTable = table( ...
        string(classOrder), ...
        truePositive, ...
        falsePositive, ...
        falseNegative, ...
        trueNegative, ...
        precision, ...
        recall, ...
        specificity, ...
        f1Score, ...
        support, ...
        'VariableNames', { ...
            'Class', ...
            'TruePositive', ...
            'FalsePositive', ...
            'FalseNegative', ...
            'TrueNegative', ...
            'Precision', ...
            'Recall', ...
            'Specificity', ...
            'F1Score', ...
            'Support'});

    % ---------------------------------------------------------------
    % Overall classifier summary
    % ---------------------------------------------------------------
    correctPredictions = sum(actualLabels == predictedLabels);
    incorrectPredictions = totalSamples - correctPredictions;

    accuracy = safe_divide( ...
        correctPredictions, ...
        totalSamples);

    macroPrecision = mean(precision);
    macroRecall = mean(recall);
    macroF1Score = mean(f1Score);

    weightedPrecision = safe_divide( ...
        sum(precision .* support), ...
        sum(support));

    weightedRecall = safe_divide( ...
        sum(recall .* support), ...
        sum(support));

    weightedF1Score = safe_divide( ...
        sum(f1Score .* support), ...
        sum(support));

    summaryTable = table( ...
        totalSamples, ...
        correctPredictions, ...
        incorrectPredictions, ...
        accuracy, ...
        macroPrecision, ...
        macroRecall, ...
        macroF1Score, ...
        weightedPrecision, ...
        weightedRecall, ...
        weightedF1Score, ...
        'VariableNames', { ...
            'TotalSamples', ...
            'CorrectPredictions', ...
            'IncorrectPredictions', ...
            'Accuracy', ...
            'MacroPrecision', ...
            'MacroRecall', ...
            'MacroF1Score', ...
            'WeightedPrecision', ...
            'WeightedRecall', ...
            'WeightedF1Score'});

    % ---------------------------------------------------------------
    % Display results
    % ---------------------------------------------------------------
    fprintf("\nClassifier Evaluation Summary\n");
    fprintf("-----------------------------\n");
    fprintf("Total samples       : %d\n", totalSamples);
    fprintf("Correct predictions : %d\n", correctPredictions);
    fprintf("Incorrect predictions: %d\n", incorrectPredictions);
    fprintf("Accuracy            : %.4f\n", accuracy);
    fprintf("Macro F1 score      : %.4f\n", macroF1Score);
    fprintf("Weighted F1 score   : %.4f\n\n", weightedF1Score);

    disp(summaryTable);
    disp(metricsTable);

    % ---------------------------------------------------------------
    % Display confusion chart
    % ---------------------------------------------------------------
    figure( ...
        'Name', 'Fault Classifier Confusion Matrix', ...
        'NumberTitle', 'off');

    confusionchart( ...
        actualLabels, ...
        predictedLabels, ...
        'Title', 'Full-Adder Fault Classification', ...
        'RowSummary', 'row-normalized', ...
        'ColumnSummary', 'column-normalized');

end


function result = safe_divide(numerator, denominator)
%SAFE_DIVIDE Prevents division-by-zero errors.

    if denominator == 0
        result = 0;
    else
        result = numerator / denominator;
    end
end